### PR TITLE
Add new poster template

### PR DESCRIPTION
**Pull request by wycliffewasonga**
Inspired by this [poster](https://twitter.com/dsc_moi/status/1331347720615862272?s=20) for [DSC Moi University](https://dsc.community.dev/moi-university/) 28th November, 2020 [Building Offline apps with USSD event](https://dsc.community.dev/events/details/developer-student-clubs-moi-university-presents-ussd/), I added a new template called, mantra, with the same design.

Below is a GIF showcasing a sample usage
Nov-26-2020 4-44-01 PM-min

@Ivy-Walobwa what do you think about this?

### CODE REVIEW

**Comment by Ivy-Walobwa** [comment]
This is nice.😊
 A field to change the University name on the DSC logo would be great

**Comment by wycliffewasonga** [comment]
> This is nice.😊
> A field to change the University name on the DSC logo would be great

Sure I will work on that.

**Comment by wycliffewasonga** [comment]
Nov-30-2020 11-51-33 PM-min

**Comment by wycliffewasonga** [comment]
The 3 activities above were mandatory cause I forgot to change the configuration for the user.name and the user.email for the repository on my machine so I ended up making commits with my other GitHub username and password. Hopefully won't happen again.

**Review by Ivy-Walobwa — APPROVED** [review]

**Pull request merged**
